### PR TITLE
PWM support

### PR DESCRIPTION
**Pull request by alxwrd**
Hello @jamesevickery 🎉! This PR is to start a conversation about PWM support (#56) and what it will look like.

This could be merged as-is to add basic speed control for a motor. It adds a `speed` parameter to the motor movement methods which sets both the frequency and the duty cycle to be the same. This is set to default to `100`; so if it's unused the functionality is the same as before.

Have you had any thoughts on what the interface for PWM should look like?

```python
motor.clockwise(speed=(50, 50))
```
or
```python
motor.clockwise(frequency=50, duty_cycle=50)
```
Or something else?

### CODE REVIEW

**Comment by jamesevickery** [comment]
Thanks so much for this!

I don't know much about PWM - could you briefly run through how this works?

I was just wondering about a couple of things:
- Does `pwm` need to be an object variable? Unless I've missed something, it's always defined and then used in `drive_motor`.
- Am I right in thinking only select GPIO ports support PWM? Would this still work if the port doesn't support PWM?

**Comment by alxwrd** [comment]
Some more thoughts on the interface for using PWM.

I like the use of a tuple for defining what speed the motor should run at:

```python
motor.clockwise(speed=(50, 50))
```

However, I also think it has the potential to make any code using `l293d` slightly unreadable. It's unclear which is the frequency and which is the cycle.

To combat this I can add a [`namedtuple`](https://docs.python.org/3/library/collections.html#collections.namedtuple) in the package namespace so users could use that if desired.

```python
import l293d

motor = l293d.DC(22, 18, 16)

# pre-define a pwm
pwm = l293d.PWM(freq=30, cycle=70)
motor.clockwise(speed=pwm)

# or use it directly in the method call
motor.clockwise(speed=l293d.PWM(freq=50, cycle=50))

# keywords aren't required
motor.clockwise(speed=l293d.PWM(50, 50))

# normal tuples should work too
motor.clockwise(speed=(20, 30))
```

**Comment by alxwrd** [comment]
@jamesevickery I think this is ready if you're happy with everything.

**Comment by jamesevickery** [comment]
@alxwrd Yeah, looks perfect thanks! :grin:

Have you tested this using actual hardware? I'd like to quickly check this works as intended with motors before merging into master

**Comment by alxwrd** [comment]
@jamesevickery Yea, I had a working set up for when I first opened the PR. I haven't had chance to test the changes from today on hardware though.

**Comment by jamesevickery** [comment]
@alxwrd Awesome thanks, I'll merge :+1:

**Pull request merged**
