### PR TITLE
pycharm_warnings

### PR DESCRIPTION
**Pull request by the-zebulan**
I got rid of some of the PyCharm warnings that came up in the `Inspection Report`.

I didn't get rid of the `Too broad exception clause` warnings since I didn't know which specific exceptions to use. It seems like the first one might be an `ImportError` that should be checked for.

Let me know what you think.

### CODE REVIEW

**Comment by jamesevickery** [comment]
Thanks for the changes 😃 

One thing I'm unsure of is the renaming of the `motor` class to `Motor` - it's a breaking change and I think `l293d.driver.motor` sort of looks better

**Comment by the-zebulan** [comment]
**https://www.python.org/dev/peps/pep-0008/#class-names**

It's a PEP8 style convention.

># Class Names
> Class names should normally use the CapWords convention.

> The naming convention for functions may be used instead in cases where the interface is documented and used primarily as a callable.

>Note that there is a separate convention for builtin names: most builtin names are single words (or two words run together), with the CapWords convention used only for exception names and builtin constants.

**Comment by jamesevickery** [comment]
Okay I'll leave it then - I'll update the README instructions to `Motor` for this branch (0.2.0 onwards)

**Comment by the-zebulan** [comment]
@jamesevickery ,

I'm just letting you know why I changed it, that's all. It's your library, you can do whatever you want!

**Comment by jamesevickery** [comment]
@the-zebulan No I appreciate it! It's normally best to stick to naming conventions, else code can get messy. You could end up with a method named `CorrectHorse` and another called `battery_staple` - it could rip a hole in the space-time continuum 😨

**Comment by the-zebulan** [comment]
@jamesevickery ,

hahaha nice xkcd reference!

Ya, you should try PyCharm sometime (if you want to). The community edition is free and it has all of these things built-in and configured as soon as you start it up. I think you can connect to remote servers through SSH too (I just checked, there is a `Remote SSH External Tools` section).

Anyways, I'll stop bugging you for tonight. It's probably very late over the pond in England.

**Comment by jamesevickery** [comment]
@the-zebulan The xkcd reference was a bit out of context, but it's xkcd nonetheless 😆 

I've got PyCharm installed but I just never got around to looking at it properly - I will soonish though.

It's 0102 so I should probably… find some more bugs to fix?

**Comment by the-zebulan** [comment]
haha 1am and bug fixes? You're dedicated!

One of the warnings I'm getting from PyCharm says this:

`Package 'yaml' is not listed in project requirements`

If I click the add it button, this last `requires` part gets added in `setup.py`

`package_data={'l293d': ['default_l293d-config.yaml']}, requires=['yaml']`

I don't think that's the correct file though (it seems to just be taking the name verbatim). I think it should probably be `'pyyaml'` instead. Then you might be able to take the `pyyaml` out of the `pip` install in `.travis.yml`. That way, `pyyaml` should be installed when you run `sudo python setup.py install` (right?)

I'm just about to go to dinner, I'll be back in an hour or so. I'll try it out when I get back (unless you already have).

**Comment by jamesevickery** [comment]
@the-zebulan Feel free to try, I'm still fairly new to `distutils` and stuff so I'm not sure how it all works - I like the sound of it being installed when `python setup.py install` is run though.

I somehow don't seem to have any (known) bugs at the moment so I have none to fix 😞 although I've started adding more tests to `tests/test_l293d.py` (see #46)

Have a nice dinner, I probably won't be awake in an hour or so. Thanks for the help today 👍

**Pull request merged**
