### PR TITLE
remove_yaml

### PR DESCRIPTION
**Pull request by the-zebulan**
https://github.com/audreyr/cookiecutter/issues/743

I came across this issue on another repo about removing YAML and it made me think of your repo. They list a few issues right at the top for the justification of removing it.

---
In your case, it also simplifies your install process if you don't have any external dependencies (other than `RPi.GPIO` but that isn't being installed by your library).

Anyways, here is a PR with the YAML config (and corresponding code) taken out and replaced by a `.ini` file using `ConfigParser/configparser` from the Python standard library.

Let me know what you think!

### CODE REVIEW

**Comment by the-zebulan** [comment]
I thought about using JSON as the config file (since Python's standard library can deal with JSON easily) but you can't put comments into a JSON file. That's why I ended up using `ConfigParser/configparser`.

**Comment by jamesevickery** [comment]
Looks good! I haven't had a chance to test it or anything but I've read through your changes.

I'll stick with the `ConfigParser/configparser` approach for now - I like having the comments there. Although I've seen people use comments in JSON by just having them as part of the data but not using it.

**Comment by the-zebulan** [comment]
I think I know what you mean about manually putting comments in json. The
issue is if you write a new json file programmatically, you can't put the
comments back in (unless you use a key like "_comments" and use the value
as your comment section).

Anyways, glad you approve of the changes. I have an old raspberrypi 2 but I
don't have the breadboard or the motors, so I have to leave that part of
the testing to you.

I've been thinking of how to rewrite some of the code so you don't have to
import driver for the start of each test and then reload it at the end of
the test. The other thing I've thought about is using a context manager to
make sure that the cleanup is run on the gpio pins (functionally the same
as your code at the bottom but it might look cleaner using 'with').

**Comment by jamesevickery** [comment]
@the-zebulan Yeah, the `_comments` thing is what I was meaning, I've seen people do that before.

Don't worry about the Pi stuff, `test_mode` stops GPIO calls and I'm pretty sure they're all working properly. If you did want to have a go at using this library, then breadboards, L293D chips and DC motors are all very cheap on Amazon or wherever. It's okay if not though - I introduced `test_mode` so that I/other people could develop on anything that can run Python.

Feel free to work on a better way of organising the tests - I'm new to Python unit testing so what I've done so far is probably a bit hacky.

The automatic `cleanup` thing sounds great although it's another thing I'm completely oblivious to, so any help would be brilliant.

**Related to this PR**, the `.ini` that is saved is called `default_l293d_config.ini`. Could the saved version just be called `l293d_config.ini` instead, without the `default_`?

**Comment by the-zebulan** [comment]
Yes, the config file can be named anything you want! I just tried to keep it the same as you had it before in case you had some reason for doing it that way.

**Comment by jamesevickery** [comment]
@the-zebulan In the previous `yaml` implementation, the default file was called `default_l293d-config.yaml`, but the config file saved to the user's home directory was just called `l293d-config.yaml`

**Comment by the-zebulan** [comment]
@jamesevickery ,

Oh, shoot. I guess I messed that up. You could just rename the `config_filename`'s default value in the `L293DConfig` class's `__init__`.

**Comment by the-zebulan** [comment]
As for the name using underscores, it's a bit of a habit since I found out the hard way (in another personal project) that you can't import a Python script with dashes in the name of the script. Python thinks the are minus signs.

In this case (loading a config file), it might not make any difference at all. Just a habit of mine (feel free to change it if you want to!).

**Comment by the-zebulan** [comment]
Ok, so just to double-check a few points.

* You want a `default_l293d_config.ini` file in the `l293d` directory (and it shouldn't ever be changed)
* You also want a copy saved to the users home directory (without the `default_` at the start of the filename)
    * If so, loading the config should prefer the file from the home directory
    * If the home directory config is missing, load the default config file
    * If both are missing, create a new default config and a new home directory config

Is that what you are thinking? Let me know if those assumptions are incorrect.

**Comment by jamesevickery** [comment]
I've removed the `default_` from the name in the commit that just referenced this PR. I've just been thinking, I'm tempted to just have the config file in the install path and let it be loaded from there. Then there could be an config method or something to load and edit the config.

**Comment by the-zebulan** [comment]
@jamesevickery , 

I just noticed a typo in the line 157 of the README, `repectively`.

**Comment by jamesevickery** [comment]
@the-zebulan Thanks, I'll fix the typo now

**Comment by the-zebulan** [comment]
@jamesevickery ,

Just saw your update about the config now (nice fix on the typo too!). I'm not really sure which way is better. It might be easier to find a config file in the home directory since it's where the terminal opens to. But if you are just going to access the config settings through importing your library, it might just be easier to have it in the installation directory. 

That's an interesting way to find the module, I wasn't aware of it. If it works, stick with it. The only thing I would warn about is, in PyCharm I get a message about `imp` being deprecated in favour of `importlib` (I put the same message in a comment at the top of `test_l293d`).

Home directory, install directory or both? I don't really have any relevant experience with this type of config file to say one way is better than the others.

**Comment by jamesevickery** [comment]
@the-zebulan I've had an idea that sounds like it should work:

- The `.ini` config stays where it is without being copied anywhere
- New methods are made in `config.py` to let the user modify the parameters' values without having to manually edit the file.
  - For example, the user is prompted for values for each parameter (or they can hit return to leave them the same) and then the new config is written to the file
- When `config.py` is run by `driver.py`, config is loaded from the file in the installation directory.

I like the idea of the config file being in the `l293d` installation directory but editable by the user - it keeps everything in one place and keeps the user's home tidy.

Tell me what you think of this - I might start having a go at this tomorrow as I don't have much time this evening. Feel free to have a go at making changes to the tests, or using the context manager thing to run `cleanup` 😀

**Pull request merged**
