### PR TITLE
update_for_travis

### LINKED ISSUE #43: Travis CI failing with ImportError
[Build 64](https://travis-ci.org/jamesevickery/l293d/builds/170746840) :x:

`ImportError: No module named l293d.driver`
...
`The command "python tests/l293d-tests.py" exited with 1.`

Not sure why this is happening, as `.travis.yml` runs `sudo python setup.py install` earlier in the script.

### PR DESCRIPTION
**Pull request by the-zebulan**
I think this PR will close #43 . I had to try a few different ideas before I could get it to work.

* I added an `__init__.py` file to the `tests` directory (for the `ImportError`)
* I updated the `.travis.yml` file
    * I used `py.test` as the testrunner (only because I see it recommended lots and I have used it before too)
    * `pip` is already installed (as per the Travis docs) so I removed the install `pip` part
    * I was having trouble with `python-yaml` install but replacing it with `pip install pyyaml` seems to work fine
* I renamed the test file to start with `test_` since that is what `py.test` expects

Hopefully this resolves the issue you were having, @jamesevickery .

### CODE REVIEW

**Comment by jamesevickery** [comment]
@the-zebulan Thanks! The build is passing now. Correct me if I'm wrong, but is this now running the test against the source code but not the installed version?

**Comment by the-zebulan** [comment]
@jamesevickery ,

Hmm, good question. I'll go check.

**Comment by the-zebulan** [comment]
@jamesevickery ,

For some reason, when testing with `py.test` I get an `ImportError` when I used the `apt-get install python-yaml` but `pip install pyyaml` seems to work still.

**Comment by the-zebulan** [comment]
@jamesevickery ,

I think that might fix your concern. Let me know if you want me to make any other changes.

**Comment by jamesevickery** [comment]
@the-zebulan So is this testing the installed version now? Build log [here](https://travis-ci.org/jamesevickery/l293d/builds/170911903)

**Comment by the-zebulan** [comment]
@jamesevickery ,

I'm not exactly sure what you mean by installed version (of `pip` right?). I've looked at the logs too but Travis installs `pip` automatically so I don't really know if installing `pip` again is even necessary.

**Comment by the-zebulan** [comment]
@jamesevickery ,

Is it because `pip` isn't installed on a RaspberryPi by default?

**Comment by jamesevickery** [comment]
@the-zebulan Sorry I was being vague - I mean are the tests running against the installed version of `l293d` or the source?

**Comment by the-zebulan** [comment]
I'm not sure what the difference is...?

**Comment by jamesevickery** [comment]
@the-zebulan I was thinking l293d had to be installed in order to run tests properly - probably wrong

**Comment by the-zebulan** [comment]
@jamesevickery ,

Looking at the logs:

```
[0K$ sudo python setup.py install
running install
running build
running build_py
creating build  ##########################################
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/l293d
copying l293d/config.py -> build/lib.linux-x86_64-2.7/l293d
copying l293d/driver.py -> build/lib.linux-x86_64-2.7/l293d
copying l293d/__init__.py -> build/lib.linux-x86_64-2.7/l293d
copying l293d/version.py -> build/lib.linux-x86_64-2.7/l293d
copying l293d/default_l293d-config.yaml -> build/lib.linux-x86_64-2.7/l293d
-
-
-
[1m============================= test session starts ==============================[0m
platform linux2 -- Python 2.7.12, pytest-3.0.0, py-1.4.31, pluggy-0.3.1
rootdir: /home/travis/build/jamesevickery/l293d, inifile:   ########################
```

It looks like the setup.py is creating this build directory and then the tests are being run there. Is that what you mean?

**Comment by jamesevickery** [comment]
Do you know how to run the test locally using this method? I ran `py.test tests/` and the output was:
```
========= test session starts ==========
platform linux2 -- Python 2.7.6 -- pytest-2.5.1
collected 0 items

===========  in 0.00 seconds ===========
```

So it looks like it's not finding/running the tests

**Comment by the-zebulan** [comment]
I run it inside of PyCharm by right-clicking on the `tests` directory and choosing `Run py.test in tests`.

**Comment by the-zebulan** [comment]
```python
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: l293d, inifile: 
collected 1 items

test_l293d.py L293D driver version 0.2.0
Can't import RPi.GPIO. Please (re)install.
Test mode has been enabled. Please view README for more info.
<module 'l293d.driver' from 'l293d/l293d/driver.py'>
.

=========================== 1 passed in 0.10 seconds ===========================
```

**Comment by the-zebulan** [comment]
Did you try just `pytest`? That's what the first example shows here: http://docs.pytest.org/en/latest/

**Comment by jamesevickery** [comment]
@the-zebulan Is `pytest` an alternative to `unittest`?

**Comment by the-zebulan** [comment]
@jamesevickery ,

Ya, it can be used to just run normal unittests (I've heard people say it has better error messages too) or you can actually write separate py.test type unittests.

Example:

```python
import unittest


class MyTestCase(unittest.TestCase):
    def test_one_plus_two(self):
        self.assertEqual(1 + 2, 3)

'''
============================= test session starts ==============================
collected 1 items

test_example.py .

=========================== 1 passed in 0.02 seconds ===========================
'''
```

Or, using py.test:

```python
def test_one_plus_two():
    assert 1 + 2 == 3


'''
============================= test session starts ==============================
collected 1 items

test_example.py .

=========================== 1 passed in 0.01 seconds ===========================
'''
```

**Comment by jamesevickery** [comment]
@the-zebulan It looks good - if you want you submit a PR using `py.test`.

As you already know, at the moment I'm only testing that `l293d` can be imported. It seems like a useless test but there have been a few times when importing has thrown exceptions on fresh installs so it's something I'd probably want to keep for now

**Comment by the-zebulan** [comment]
@jamesevickery ,

I understand, more tests the better! I was thinking about maybe trying to help make your project Python 3 compatible too. I was just looking at the `Inspection Report` in PyCharm and saw a few things that might need fixing first.

l293d_fixes

Do you mind if I send a PR with some of those fixes first?

**Comment by jamesevickery** [comment]
@the-zebulan Yeah that sounds great thanks - as long as it's still Python 2 compatible 😄

**Comment by the-zebulan** [comment]
@jamesevickery ,

Ya, I'll just do the Python 2 stuff first. Later on I can work on the Python 3 compatibility in a different branch.

**Comment by jamesevickery** [comment]
@the-zebulan Yes sorry I thought you meant the list was stuff to do in order to make it Python 3 compatible

**Comment by the-zebulan** [comment]
@jamesevickery ,

Sorry, I should have been more specific. Ya, it's just warnings that PyCharm shows automatically. It's kind of a game for me to try and get rid of them all. The warnings have helped me learn to write better code, I'm a big PyCharm fan!

**Comment by jamesevickery** [comment]
@the-zebulan I'm just using an Ubuntu server with SSH - and Remote Systems Explorer for Eclipse and a few online IDEs with SFTP support.

If you're making formatting changes according to PyCharm, it might be worth running `flake8` to check the linting

**Comment by the-zebulan** [comment]
PyCharm has PEP8 checks built-in. I'm not sure if it uses `flake8` but since you have travis setup to check `flake8`, I'll check to make sure there aren't any issues.

**Comment by jamesevickery** [comment]
@the-zebulan Don't worry too much about it locally, you'll see when you submit the PR whether on not flake8 is complaining

**Comment by the-zebulan** [comment]
@jamesevickery ,

Yep, sounds good.

I like being able to do all the git/GitHub functions without leaving my IDE (cloning, pull requests, branching, etc). There are so many great features, I still probably don't know half of them.

**Comment by jamesevickery** [comment]
@the-zebulan By the way, I had a quick look into flake8 I think it uses PEP8

**Comment by the-zebulan** [comment]
@jamesevickery ,

Ya, that's what it does. It just didn't seem to catch everything since there were a few PEP8 warnings that PyCharm picked up that `flake8` didn't seem to warn about (maybe there are extra settings that aren't being used currently).

**Comment by the-zebulan** [comment]
Question: This inner `for` loop doesn't seem to make much sense (plus, PyCharm is warning because you used the same variable name `pin` for both `for` loops).

```python
        for pin in pins:
            pin_int = int(pin)
            if pin_int not in valid_pins and force_selection is False:
                err_str = (
                    "GPIO pin number must be from list of valid pins: %s"
                    "\nTo use selected pins anyway, set force_selection=True "
                    "in function call." % str(valid_pins))
                raise ValueError(err_str)
            for pin in pins_in_use:
                if pin in pins:
                    raise ValueError('GPIO pin {} already in use.'.format(
                        str(pin)))
```

Is the second `for` loop simply checking if `pin in pins_in_use`?

**Comment by jamesevickery** [comment]
@the-zebulan Yes I think so - I forgot I was already in a `for pin in pins` loop

**Comment by the-zebulan** [comment]
That's what I guessed. I made the change (and a bunch of other ones) in
that new PR.

**Pull request merged**
